# Generated by Django 5.0 on 2023-12-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('roll', models.BigAutoField(primary_key=True, serialize=False)),
                ('ageInSeconds', models.BigIntegerField()),
                ('dataField', models.BinaryField()),
                ('boolean', models.BooleanField()),
                ('char', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('dateTime', models.DateTimeField()),
                ('deci', models.DecimalField(decimal_places=6, max_digits=15)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('fileField', models.FileField(upload_to='')),
                ('filePath', models.FilePathField(path='/home/nayeemtby/dev/learn/phitron/web/django_week4/web_prac41')),
                ('floating', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('integer', models.IntegerField()),
                ('json', models.JSONField()),
                ('positiveBigInt', models.PositiveBigIntegerField()),
                ('slug', models.SlugField()),
                ('article', models.TextField()),
                ('url', models.URLField()),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='OnnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_pract.practicemodel')),
            ],
        ),
    ]
