# Generated by Django 5.0 on 2023-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isComplete', models.BooleanField(auto_created=True, default=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('assignedDate', models.DateField()),
                ('categories', models.ManyToManyField(to='task_category.taskcategory')),
            ],
        ),
    ]
